version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: linkup_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkup_network

  neo4j:
    image: neo4j:5
    container_name: linkup_neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/linkup_neo4j_password
    ports:
      - "7474:7474"  # Interface web
      - "7687:7687"  # Bolt (connexion API)
    volumes:
      - neo4j_data:/data
    networks:
      - linkup_network

  redis:
    image: redis:7
    container_name: linkup_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - linkup_network

  backend:
    build: ./linkupback
    container_name: linkup_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://linkup:linkup_password@postgres:5432/linkup_db
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: linkup_neo4j_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - neo4j
      - redis
    networks:
      - linkup_network

networks:
  linkup_network:
    driver: bridge

volumes:
  postgres_data:
  neo4j_data:
  redis_data: